### ISSUE TITLE
[feature] Create a hooking mechanism for data collectors

### ISSUE THREAD

**Issue by vmoens** [facebookresearch/rl#190]
## Description
It would be good to have a way of sending commands to running environments through the data collectors, via a hooking mechanism for instance (eg a function run after each rollout) or simply call it with something like
```
datacollector.map_fn("my_fn_name", list_args, list_kwargs)
```

## Work plan

- [ ] Add a `DataCollector.get_distant_attr(attr)` method
- [ ] Add a `DataCollector.map_fn(method_name, list_of_args, list_of_kwargs)`
- [ ] Add a pre-collection and post-collection hook

cc @yidingjiang
